server:
  port: 8031


spring:
  application:
    name: chat-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: pnu-cse
    topic : studyhub
    pub-topic-name: send
    sub-topic-name: receive

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${server.port}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
tcp:
  server:
    host: localhost
    port: 8099
    connection:
      poolSize: 30

logging:
  level:
    pnu.cse.studyhub: DEBUG