property :
  ignoreNullWsContainer : true
#Redis Cache
spring:
  redis:
    host: 0.0.0.0
    port: 6379

server:
  ssl:
    enabled : true
    key-store: src/main/resources/donu-keystore.jks
    key-store-password: test1234
    key-store-type: PKCS12
    key-alias: donu-keystore
  port: 8443

tcp:
  server:
    host: 1
    port: 1
    connection:
      poolSize: 1