property :
  ignoreNullWsContainer : true

server:
  ssl:
    enabled : true
    key-store: src/main/resources/donu-keystore.jks
    key-store-password: test1234
    key-store-type: PKCS12
    key-alias: donu-keystore
  port: 8059

tcp:
  server:
    host: localhost
    port: 8099
    connection:
      poolSize: 30