spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            AllowedOriginPatterns: "http://localhost:*"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: auth-service
          uri: http://${EC2_IP}:8011
          predicates:
            - Path=/auth/**
        - id: chat-service
          uri: http://${EC2_IP}:8031
          predicates:
            - Path=/chat/**
        - id: room-service
          uri: http://${EC2_IP}:8081
          predicates:
            - Path=/room/**

token:
  access_expired_time: 3600000
  secret_key: ${SECRET_TOKEN}
  refresh_expired_time: 3600000