spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://localhost:3002"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
      routes:
        - id: auth-service-post
          uri: http://${EC2_IP}:8011
          predicates:
            - Path=/auth/**
            - Method=POST,OPTIONS
        - id: auth-service
          uri: http://${EC2_IP}:8011
          predicates:
            - Path=/auth/**
            - Method=GET,PATCH
          filters:
            - AuthorizationHeaderFilter
        - id: chat-service
          uri: http://${EC2_IP}:8031
          predicates:
            - Path=/chat/**
          filters:
            - AuthorizationHeaderFilter
        - id: room-service
          uri: http://${EC2_IP}:8081
          predicates:
            - Path=/room/**
          filters:
            - AuthorizationHeaderFilter
        - id: signaling-service
          uri: wss://${EC2_IP}:8091
          predicates:
            - Path=/socket/**

token:
  access_expired_time: 3600000
  secret_key: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  refresh_expired_time: 3600000