server:
  port: 8091

spring:
  application:
    name: state-service
  redis:
    host: 127.0.0.1
    port: 6379
#  integration:
#    tcp:
#      port: ${server.port}

tcp:
  server:
    port : 8099
logging:
  level:
    pnu.cse.studyhub: INFO
