spring:
  application:
    name: state-service
  redis:
    host: redis-state
    port: 6380
#  integration:
#    tcp:
#      port: ${server.port}

tcp:
  server:
    port : 8099
  room:
    host : sgs-room
    port : 8081
    connection :
      poolSize : 30
logging:
  level:
    pnu.cse.studyhub: INFO
