spring:
  application:
    name: state-service
  redis:
    host: redis-state
    port: 6379
#  integration:
#    tcp:
#      port: ${server.port}

tcp:
  server:
    port : 8099
  room:
    host : sgs-room
    port : 8089
    connection :
      poolSize : 30
  signaling:
    host: sgs-signaling
    port: 8058
    connection:
      poolSize: 10
  auth:
    host: sgs-auth
    port: 8019
    connection:
      poolSize: 10
logging:
  level:
    pnu.cse.studyhub: DEBUG
